# Step 1: Build React App
FROM node:18-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile
COPY . .


# Pass environment variables at build time
ARG VITE_API_BASE_URL
ARG VITE_CLOUDINARY_API_KEY
ARG VITE_CLOUDINARY_API_SECRET
ARG VITE_CLOUDINARY_CLOUD_NAME
ARG VITE_CLOUDINARY_PRESET
ARG VITE_STRIPE_PK
ARG VITE_GOOGLE_AUTH_CLIENT_ID

# Set environment variables in the container
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_CLOUDINARY_API_KEY=$VITE_CLOUDINARY_API_KEY
ENV VITE_CLOUDINARY_API_SECRET=$VITE_CLOUDINARY_API_SECRET
ENV VITE_CLOUDINARY_CLOUD_NAME=$VITE_CLOUDINARY_CLOUD_NAME
ENV VITE_CLOUDINARY_PRESET=$VITE_CLOUDINARY_PRESET
ENV VITE_STRIPE_PK=$VITE_STRIPE_PK
ENV VITE_GOOGLE_AUTH_CLIENT_ID=$VITE_GOOGLE_AUTH_CLIENT_ID

RUN npm run build
CMD [ "npm", "run", "dev" ]
