export const AuthMessages = {
  SUCCESS: {
    RESET_LINK_SEND: "Password reset link sent successfully.",
    LOGIN: "Logged in successfully.",
    LOGOUT: "Logged out successfully.",
    SIGNUP: "Account created successfully.",
    VERIFY_OTP: "OTP verified successfully.",
    RESEND_OTP: "OTP resent successfully.",
    VALIDATE_OTP: "Valid 6-digit OTP entered.",
    PASSWORD_VERIFIED: "Current password verified successfully.",
    PASSWORD_CHANGE: "Password changed successfully.",
  },
  ERROR: {
    INVALID_OTP: "Invalid OTP!",
    RESET_LINK_SEND: "Failed to send password reset link.",
    RESET_LINK_GET: "Invalid or expired password reset link. Please try again.",
    LOGIN: "Login failed. Please check your credentials and try again.",
    SIGNUP: "Signup failed. Please try again.",
    GOOGLE_SIGNUP: "Google signup failed. Please try again.",
    LOGOUT: "Logout failed. Please try again.",
    VERIFY_OTP: "OTP verification failed. Please try again.",
    RESEND_OTP: "Failed to resend OTP. Please try again.",
    PASSWORD_RESET: "Failed to reset password",
    PASSWORD_CHANGE: "Failed to change password. Please try again.",
  },
};
