export enum AuthMessages {
  RESET_LINK_SEND_SUCCESS = "Password reset link sent successfully.",
  FORGOT_PASSWORD_FAILED = "Forgot password failed!",
  LOGIN_FAILED = "Login failed. Please try again.",
  SIGNUP_FAILED = "Signup failed. Please try again.",
  SIGNUP_SUCCESS = "Successfully signup",
  GOOGLE_SIGNUP_FAILED = "Signup failed. Please try again.",
  LOGIN_SUCCESS = "Successfully login",
  LOGOUT_SUCCESS = "Successfully logout",
  LOGOUT_FAILED = "Logout failed. Please try again.",
  VERIFY_OTP_SUCCESS = "Otp verification success.",
  VERIFY_OTP_FAILED = "The OTP verification failed!",
  RESEND_OTP_SUCCESS = "OTP resend successfully.",
  RESEND_OTP_FAILED = "Failed to resend OTP.",
}
